
##################
### WALLPAPERS ###
##################
preload = $HOME/.local/share/backgrounds/cassette01.jpg
wallpaper = eDP-1, $HOME/.local/share/backgrounds/cassette01.jpg
wallpaper = HDMI-A-1, $HOME/.local/share/backgrounds/cassette01.jpg
