
##################
### WALLPAPERS ###
##################
preload = $HOME/.local/share/backgrounds/cassette01.jpg
wallpaper = eDP-1, $HOME/.local/share/backgrounds/cassette01.jpg
#wallpaper = DP-1, ~/Pictures/backgrounds/dark_wallpaper.png
