
##################
### WALLPAPERS ###
##################
preload = $HOME/.local/share/backgrounds/cube_dark_texture_119956_1920x1080.jpg
wallpaper = eDP-1, $HOME/.local/share/backgrounds/cube_dark_texture_119956_1920x1080.jpg
#wallpaper = DP-1, ~/Pictures/backgrounds/dark_wallpaper.png
