
[opener]
edit = [
  { run = 'fish -c "nvd $@" ', for = "unix", orphan = true, desc = "Editar en nvim" },
  #{ run = 'rio -e helix $@', orphan = true, for = "unix", desc = "Editar" },
  #{ run = 'rio -e micro $@', orphan = true, for = "unix", desc = "Editar en micro" },
  #{ run = 'zeditor $@', orphan = true, for = "unix", desc = "Editar en zed" },
]
open = [
  { run = 'kitty --working-directory="$(dirname "$@")"', orphan = true, desc = "Abrir en kitty", for = "unix" },
  { run = 'fish -c "nvd ."', orphan = true, desc = "Abrir en neovide", for = "unix" },
  { run = 'nemo $@/..', orphan = true, desc = "Abrir en navegador de archivos", for = "unix" },
  #{ run = 'kitty fish -c "helix $@/.."', orphan = true, desc = "Abrir", for = "unix" },
  #{ run = 'ghostty --working-directory="$@" --command="helix ."', orphan = true, desc = "Abrir", for = "unix" },
  #{ run = 'rio -w $@ -e helix .', orphan = true, desc = "Abrir", for = "unix" },
  #{ run = 'zeditor .', orphan = true, desc = "Abrir en zed", for = "unix" },
  #{ run = 'rio -w $@/..', orphan = true, desc = "Abrir en terminal", for = "unix" },
  #{ run = 'ghostty --working-directory="$@/.."', orphan = true, desc = "Abrir en terminal", for = "unix" },
]
